import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { SettingsProvider } from "@/context/settings/settings-provider";
import { SettingsValueProps } from "@/context/settings/types";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const defaultSettings: SettingsValueProps = {
  theme: "light",                
  enableSystem: true,
  language: "fa",               
  themeStretch: false,
  themeDirection: "rtl",       
  themeContrast: "default",      
  themeLayout: "vertical",        
  themeColorPresets: "default",   
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <SettingsProvider defaultSettings={defaultSettings}>
          <ThemeProvider attribute="class" defaultTheme="light">
            {children}
          </ThemeProvider>
        </SettingsProvider>
      </body>
    </html>
  );
}
